travis:
  secure:
    BINSTAR_TOKEN: aJzcfMPtq9gQyDWVJ5/88By+ktOKxhY9+Fnx2CC1jAZHA7fV1HWcJFo/If3WsMBbkSzvAthnAs1k25SHJ6bJMsLFdjBC4nxC40J8fYk5iRsuvomyaEABf3YP6jKkQhxEJ9KvD9OdeVnpR2+YFNNLueSe/40lz80RKA1DS7oHimxaIzvqZh/Q/Tkjiix+giEAL/buATrIXuPhqNnybxFvJQqY62B2GroGGL+AzZZRv0lJJsvxSdWtsaFIDJJpRPEa+ckV05Y0Vo4wwfu0NGVeOiRe0sDM1J/4CIjaHx4Z2hGNhcO6OLYbAebrjblr3J7PtoO/PppXtywTgiTN9DYXhDhZEvb2LjiekfQpHi55MHMB+y3npR08p3WqwEJTeZVvl4aXHH1YjxC4UircX2JQJ24Xpyv5aOON4+G5zQhcDjkYCTw0eTWxnTFPUa/JqV41dCxbeDd+c3xEeRqXDWsth8GZFYsVnAwsjowSZ5NyZUiMaRZszLggYqJ2MrhbnfSMx8fOfvZvwXNIOC7PK/ZihpwnWjiw1pz1hIMZJApyITsot3LkdKPOmDF+ht02jm2tKCAjh3s/BafWPEjftxSIRI7YFO6bEOmeKdgNqHVvCFg6VTdZx1Bq5sbAvMF4dpYl3BgcHW2LLFW0KMLIUz8IVAfYzH4w9cwuCdrCDJ3ob0k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
