travis:
  secure:
    BINSTAR_TOKEN: mQbtI/ckYJebRJzS86yRIUx9qufeRbKIn4FwXan/Q9o7b23AFoWMkQTTJz0bjJqUmntINJ7H1rAcno0VF1hNx6awVNCnZwHeim475d+JgCR8N3KpBHFzdqzgOEyQGfvWe/ZItL4ZjNBWtdCLZLwhm2FoEw/tmJKr8U3OyexnzghqPMXRuHKKfko0DWMz3n3lsbmvbm5sPMD0SEH8Rc5q+JWA/g5tp4H7wfTLbOo46qG0NbccqXrOCz3OoOG4IYyt+ufpqJ89L+vMv2bBa5qmdUoRr8LdmTOz4B1tw9bdtthZc7ADHH7IqLluBxe+l5us31KaeCB83Q7wQto2AYIk8730yNwLXB7bqPhbrZjVtz1gGlSlck29gb+YfOZPH2Q3sQD0rxl+pLqaiDNHXB8ywCPvh3TE4vqxT1ukWfSGQ9CmWms8bkAgy+Lcjsc5YbOIKrZ0kgtovPZ//1cnH0Usg0gZcBgmbgJe+PAAdVMmLrgqRNYZmWE9bn2hOzjsLebV9kBOLHWWWa6si66EkJlqmcsjY3EHhO94uw/0v8lg2vrUavpklSlGaodnulVZBGkqQaK8+nmvv0FR/sy4TKagY4LEOGr5iJn09uFFFKrRI6+s8NNOaYw/Tdojfz8ucdrnXHhStZZXc9sgFt8jieihKIJa6u6Japyff/u3JIL8+aw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
