travis:
  secure:
    BINSTAR_TOKEN: jASQPpltRTE5WcOthtwOSWMLrYJ/cq/Zjth1NWoGU9qaXH8xACPVYsOJ9oNyxdUpGdXOflpN1UxXQpQ0Rce5s0lFg6rAewXopSheR92I4BjenOTu1p45ey0MuISSQhDjrQavN+hbeTvu/QQ1mOlTaKewHOcM+I2jQhdRWZLVFvC+G54x69h+2nqgDDv+Sh4yGu2H+YLwHk4dcGrtsjZpkd1n/txHRapg1GhAbsx4hjTf268KEQEIVhmNDE1TE6BZmAKBGVlW3m1X1fraphDY8mLIPgQrtFqnLo4FKQ1AtoEIv2IjBEfCzsU4L+5aaZ08yNRqE7kHSVmwulI/xQh19FoxtLzf4k1weNK5apevmM8N0YFcEh1JosYAMOO1/p70lJPoD47tCmjLmTnHOmphoaXz2PP/Weuh090EQi3c7r7jLjJKaz4ULaaBpdIMES4tM93lIVUG/lofgDBZoq3nxputWjulDxpyhpyGUKq83OWLQW617Oj2/Fdb7ddU4xqG0Q+dUuQAfKvl0lxoqs6+glnLzwf1et9KRQe2FrorIC0KubiXoYvsULhJyAxAT0dszgncYB47bAhvbh/LC17E92l66wbAKzZgZrDhq2L7p61wf/NMQd6nZOr95aOAGKACeBizTD3/ebIKW5ewMny/JBmiBkk8zX1k9ANJVR7UW+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
